name: Publish

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Build Client App
        working-directory: ./src/KafkaFlow.Admin.Dashboard/ClientApp
        run: |
          npm install
          npm run lint
          npm run build:prod

      - name: Pack
        run: dotnet pack ./KafkaFlow.sln -c Release /p:Version=${{ github.event.release.tag_name }} -o ./drop

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./drop/**/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate

      - name: Print Version
        run: echo ${{ github.event.release.tag_name }}
